name: "Omada Controller"
version: "6.0.4"
slug: "omada_controller"
description: "TP-Link Omada Software Controller"
url: "https://github.com/ivmreg/ha_omada_controller"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
host_network: true
log_level: info
map:
  - share:rw
schema:
  omada_data_dir: "str?"
options:
  omada_data_dir: "/data/omada"