name: "Omada Controller"
version: "6.0.8"
slug: "omada_controller"
description: "TP-Link Omada Software Controller"
url: "https://github.com/ivmreg/ha_omada_controller"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
host_network: false
ports:
  8080/tcp: 9080     # Omada mgmt HTTP
  8443/tcp: 9443     # Omada mgmt HTTPS
  8843/tcp: 9843     # Omada portal HTTPS
  8880/tcp: 9880     # Omada portal HTTP
  27017/tcp: 27017   # MongoDB
log_level: info
map:
  - share:rw
schema:
  omada_data_dir: "str?"
options:
  omada_data_dir: "/data/omada"